# Generated by Django 5.1.1 on 2024-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('crime_description', models.TextField()),
                ('date_of_crime', models.DateField()),
                ('arrest_date', models.DateField()),
                ('photo', models.ImageField(upload_to='criminals/')),
            ],
        ),
    ]
